# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
os: linux
dist: xenial  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email: true

env:
  matrix:
    - ROS_DISTRO=kinetic TEST=clang-format
    - ROS_DISTRO=kinetic ROS_REPO=ros
    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/ros-planning/moveit/kinetic-devel/moveit.rosinstall

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - source .moveit_ci/travis.sh
